### PR TITLE
Update Workshop.md

### PR DESCRIPTION
**Pull request by ddunn2**

### CODE REVIEW

**Comment by ianpartridge** [comment]
These instructions are in README.md

**Comment by ddunn2** [comment]
We know, Lloyd requested they be moved into a single file.

**Comment by ianpartridge** [comment]
The README also contains the instructions on cloning the repo and testsuite so that would need moving across too, I think.

**Comment by ddunn2** [comment]
I've already moved them across, see the second commit. 
I realised I had missed them in my initial commit and went to update it but I think I updated the PR as you closed it, so you may not have seen the second commit.

**Comment by ianpartridge** [comment]
OK cool, that makes sense. We can merge this as-is but I wonder if it would be better to move the contents of Workshop.md to README.md entirely, so all the instructions are on the front page of the repo. What do you think?

**Pull request closed without merging**
